spring:
  datasource:
    #连的使授权服务的数据库，其实真实环境，二者必然是分开的，注册、管理用户信息必定是oauth2那边做的
    url: jdbc:mysql://47.98.149.207:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 158d3e483dc2
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://47.98.149.207:8000/eureka/
      #defaultZone: http://localhost:8000/eureka/

ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000
#oauth2的配置
oauth2:
  client-id: c1
  client-secret: secret
  grant-type: password
  uri: /oauth/token
# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）