spring:
  datasource:
    url: jdbc:mysql://47.98.149.207:3306/mall-product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 158d3e483dc2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 日期全局配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 加载Mybatis映射文件,默认开启了下划线转驼峰设置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 配置slq打印日志
logging:
  level:
    com:
      mall:
        product:
          mapper: debug


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://47.98.149.207:8000/eureka/

ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000
# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
