server:
  port: 8084
spring:
  application:
    name: mall-product-dev
  datasource:
    url: jdbc:mysql://47.98.149.207:3306/mall-product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 158d3e483dc2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # No operations allowed after connection closed
      # mysql5.0针对超长时间数据库连接做了一个处理，即一个数据库在无任何操作情况下过8小时会
      #自动把这个连接关闭 ，而数据库连接池并不知道该 connection 已经失效，
      #这个时候你请求数据库链接，连接池会将失效的 connection 给你，so~，SpringBoot 温柔的告诉你
      # 连接池最大连接数，默认是10
      maximum-pool-size: 60
      # 连接超时时间默认是 30000(30秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 30000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期
      max-lifetime: 60000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
  redis:
    host: 175.27.134.153
    port: 6379
    database: 2
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
  jackson:
    # 日期全局配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 加载Mybatis映射文件,默认开启了下划线转驼峰设置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 配置slq打印日志
logging:
  level:
    com:
      mall:
        product:
          mapper: debug

eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 47.98.149.207
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}

  client:
    service-url:
      defaultZone: http://47.98.149.207:8000/eureka/,http://175.27.134.153:8000/eureka/

ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000
# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
