spring:
  application:
    name: mall-order
  datasource:
    url: jdbc:mysql://localhost:3306/mall-order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082

#logging:
#  level: debug
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://47.98.149.207:8000/eureka/
